[project]
name = "wanderland-download"
version = "0.1.0"
description = "WanderLand - Download Module"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.3.2",
    "laspy>=2.7.0",
    "open3d>=0.19.0",
]
